name: output
on: [issues, workflow_dispatch]
jobs:
  outputDetail:
    runs-on: windows-latest
    steps:
      - name: Output issue detail
        run: echo "Issue number ${{ github.event.issue.number }}"
             echo "issue title ${{ github.event.issue.title }}"